### ISSUE TITLE
CORSの設定をしてほしい

### ISSUE THREAD

**Issue by aoba-s** [AKABANEDAI-FES/2024-contest#10]
### 🧐 バグの詳細

Unityのプロジェクトを（一旦見せる用に）デプロイしたところ、APIにアクセスする際CORSエラーが出てしまう。https://akabanedai-fes.com を許可してほしい。

### 🥰 期待される動作

CORSエラーが出ない。

### 🖋️ 補足事項

https://qiita.com/studio_haneya/items/8b584fa605b3788d0642

**Comment by Takuho3650** [comment]
一旦動く状態になったと思うので試してください

**Comment by aoba-s** [comment]
問題なく動きました👍
