### ISSUE TITLE
APIキー認証を追加してほしい

### ISSUE THREAD

**Issue by aoba-s** [AKABANEDAI-FES/2024-contest#13]
### 💡 提案の概要

APIキー認証を追加して、キーがないとアクセスできないようにしたい。

### 🥳 提案の目的

悪意あるユーザーからのリクエストが防げる。

### 🖋️ 補足事項

この記事とか参考になるかも？
https://qlitre-weblog.com/django-rest-framework-generate-api-key

**Comment by Takuho3650** [comment]
それだったら全部Adminでのログイン必須で統一する？(今は無効化してるスタッフ用APIがその仕様だった)

ちなみに認証セッションの有効期間は2週間らしい

**Comment by aoba-s** [comment]
試してみた感じいけそうだからそれでお願いしていい？

**Comment by Takuho3650** [comment]
対応済み、確認お願いします

**Comment by aoba-s** [comment]
問題なきかと思います！
本番環境に反映されたら試してみるので教えてほしい🙏

**Comment by Takuho3650** [comment]
反映するの忘れてました()
更新しときました

**Comment by aoba-s** [comment]
フロントエンドでも問題なく動作しました👍
