### ISSUE TITLE
URLのスペルがstaffでなくstuffになっている

### ISSUE THREAD

**Issue by aoba-s** [AKABANEDAI-FES/2024-contest#5]
### 🧐 バグの詳細

下記URLのスペルがstaffでなくstuffになっている。
- /api/v1/stuff-category/
- /api/v1/stuff-plan/
- /api/v1/stuff-voter/
- /api/v1/stuff-votelog/
- /api/v1/stuff-latestvote/

### 🥰 期待される動作

stuffがstaffになる。

### 📝 バグ発生までの手順

http://127.0.0.1:8000/api/v1/
ここをみた時に気がついた。

**Comment by Takuho3650** [comment]
すみません直し忘れてました（）

**Comment by Takuho3650** [comment]
対応済み

**Comment by aoba-s** [comment]
ありがとう！
