### ISSUE TITLE
N+1問題が起きていないか確認する

### ISSUE THREAD

**Issue by aoba-s** [AKABANEDAI-FES/2024-contest#7]
### 🧐 バグの詳細

**発生を確認したわけではないが**
N+1問題が起きていないか確認しておく必要がある

### 🥰 期待される動作

N+1問題が起きていない

### 🖋️ 補足事項

https://moocs.iniad.org/courses/2023/CS121/09/03

**Comment by Takuho3650** [comment]
ひとまず当日使用するAPI分は確認しました、問題なさそうです(ちょっと意外)
スタッフ用(エンドポイントにstaffって付くやつ)のもGETのみ確認しましたが、latest_vote用がN+1になってました。
ただこの前作ってもらったAdminサイト使う場合は発生しなかったので、問題なしかと思います。

GET
api/v1/voter?user_id=user_id
発生なし

POST
api/v1/voter
発生なし

POST
api/v1/vote
発生なし

GET
api/v1/total
発生なし

**Comment by aoba-s** [comment]
ありがとう！

**Comment by aoba-s** [comment]
当日、スタッフ用のlatest_voteにアクセスしたらDB負荷上がっちゃった！とかならないように、一旦そこのエンドポイントだけ塞いでおいて欲しい
念には念をみたいなところ

**Comment by Takuho3650** [comment]
封鎖しときました

**Comment by aoba-s** [comment]
ありがとう！助かります🙏
